version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Map host port 8080 to container port 80
    volumes:
      - ./php:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # Change as needed
      MYSQL_DATABASE: db  # Change as needed
      MYSQL_USER: db_user      # Change as needed
      MYSQL_PASSWORD: root  # Change as needed
    ports:
      - "3306:3306"  # Map host port 3306 to container port 3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d  # Mount your SQL files/configurations

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"  # Map host port 8081 to phpMyAdmin container port 80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password  # Must match with db container's root password
    depends_on:
      - db
